[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
[build]
  functions = "functions/routers"
